/*
 * frontend_extra.h — DVB enum values, struct types, and ioctl numbers used
 * by TBS drivers but missing from the upstream Linux kernel's headers.
 *
 * This header is HAND-WRITTEN, not copied from upstream. It is one of two
 * files in src/ that aren't part of the upstream sync (the other is Kbuild,
 * which is auto-generated by sync-upstream.sh).
 *
 * SCOPE
 * -----
 * Define only values that don't exist in any stock kernel header.
 * Naming inconsistencies (e.g. TBS's APSK_8L vs the kernel's APSK_8_L) are
 * resolved by patches in patches/, not here.
 *
 * VALUES
 * ------
 * The numeric values below DO NOT match TBS's own kernel header
 * (tbsdtv/linux_media include/uapi/linux/dvb/frontend.h), because TBS
 * reordered enum fe_code_rate and enum fe_modulation in their kernel.
 * For example TBS has FEC_29_45 = 31, but stock kernel uses position 31
 * for FEC_4_15. We can't match TBS's values without colliding with
 * existing stock kernel values that drivers also reference.
 *
 * Instead, we assign values STRICTLY ABOVE the stock kernel's maximum
 * enum value (FEC_7_15 = 32 for fe_code_rate, APSK_64_L = 20 for
 * fe_modulation). This guarantees no collision with stock values.
 *
 * Userspace consequences:
 *   - DVB-aware tools recompiled against the stock kernel will see these
 *     as "unknown enum value" rather than a wrong-but-valid value.
 *     This is the safer failure mode.
 *   - TBS-aware userspace tools (built with TBS's kernel headers) will
 *     see different numeric values than us — but in practice, those tools
 *     read the symbolic name via libdvbv5 lookup tables, not raw integers.
 *
 * If a future stock kernel adds these values, the matching definitions
 * here become redundant (the #ifndef guards make them harmless).
 */

#ifndef _FRONTEND_EXTRA_H_
#define _FRONTEND_EXTRA_H_

#include <linux/types.h>
#include <linux/ioctl.h>
#include <linux/dvb/frontend.h>

/*
 * TBS-custom ioctl payload structs and ioctl numbers, used by:
 *   - tbsci.c / tbsmod.c (their own miscdevice ioctl handlers)
 *   - tbsecp3-ci.c, etc. (also miscdevice handlers)
 *
 * These are NOT in stock kernel headers. The actual struct field layouts
 * here match TBS's definitions in include/uapi/linux/dvb/frontend.h on
 * tbsdtv/linux_media. The ioctl numbers (cmd 'o' / 90..98) likewise match.
 *
 * TBS-aware userspace tools that issue these ioctls expect the same
 * struct layouts and cmd numbers, so faithfulness here matters more than
 * for the enum extensions above.
 */
struct ecp3_info {
	__u8  reg;
	__u32 data;
};

struct mcu24cxx_info {
	__u32 bassaddr;
	__u8  reg;
	__u32 data;
};

struct usbi2c_access {
	__u8 chip_addr;
	__u8 reg;
	__u8 num;
	__u8 buf[8];
};

struct eeprom_info {
	__u8 reg;
	__u8 data;
};

#ifndef FE_ECP3FW_READ
#define FE_ECP3FW_READ    _IOR('o', 90, struct ecp3_info)
#define FE_ECP3FW_WRITE   _IOW('o', 91, struct ecp3_info)
#endif

#ifndef FE_24CXX_READ
#define FE_24CXX_READ     _IOR('o', 92, struct mcu24cxx_info)
#define FE_24CXX_WRITE    _IOW('o', 93, struct mcu24cxx_info)
#endif

#ifndef FE_REGI2C_READ
#define FE_REGI2C_READ    _IOR('o', 94, struct usbi2c_access)
#define FE_REGI2C_WRITE   _IOW('o', 95, struct usbi2c_access)
#endif

#ifndef FE_EEPROM_READ
#define FE_EEPROM_READ    _IOR('o', 96, struct eeprom_info)
#define FE_EEPROM_WRITE   _IOW('o', 97, struct eeprom_info)
#endif

#ifndef FE_READ_TEMP
#define FE_READ_TEMP      _IOR('o', 98, __s16)
#endif

/*
 * Modulation values used by DVB-S2X drivers, missing from stock
 * <linux/dvb/frontend.h>. Assigned values 21+ (stock max APSK_64_L = 20).
 */
#ifndef APSK_128
#define APSK_128    21
#endif
#ifndef APSK_128_L
#define APSK_128_L  22
#endif
#ifndef APSK_256
#define APSK_256    23
#endif
#ifndef APSK_256_L
#define APSK_256_L  24
#endif
#ifndef APSK_1024
#define APSK_1024   25
#endif

/*
 * FEC code rates used by DVB-S2X, missing from stock kernel.
 * Assigned values 33+ (stock max FEC_7_15 = 32).
 *
 * The FEC_R_* values are TBS-specific raw numeric encodings used by some
 * frontends (mxl58x, m88rs6060, stid135) — they map to internal chip
 * register values for non-standard code rates.
 */
#ifndef FEC_29_45
#define FEC_29_45  33
#endif
#ifndef FEC_31_45
#define FEC_31_45  34
#endif
#ifndef FEC_R_58
#define FEC_R_58   35
#endif
#ifndef FEC_R_5E
#define FEC_R_5E   36
#endif
#ifndef FEC_R_60
#define FEC_R_60   37
#endif
#ifndef FEC_R_62
#define FEC_R_62   38
#endif

#endif /* _FRONTEND_EXTRA_H_ */
